// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

// ===================================
// InitPayload
// ===================================

func (v *InitPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			v.Name = string(in.String())
		case "symbol":
			v.Symbol = string(in.String())
		case "baseUri":
			v.BaseURI = string(in.String())
		case "trackMinted":
			v.TrackMinted = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v InitPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"name":`)
	out.String(v.Name)
	out.RawString(`,"symbol":`)
	out.String(v.Symbol)
	out.RawString(`,"baseUri":`)
	out.String(v.BaseURI)
	out.RawString(`,"trackMinted":`)
	out.Bool(v.TrackMinted)
	out.RawByte('}')
}

func (v InitPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

func (v *InitPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&r)
	return r.Error()
}

// ===================================
// SafeTransferFromPayload
// ===================================

func (v *SafeTransferFromPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			v.From = string(in.String())
		case "to":
			v.To = string(in.String())
		case "id":
			v.Id = string(in.String())
		case "amount":
			v.Amount = uint64(in.Uint64())
		case "data":
			v.Data = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v SafeTransferFromPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"from":`)
	out.String(v.From)
	out.RawString(`,"to":`)
	out.String(v.To)
	out.RawString(`,"id":`)
	out.String(v.Id)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawString(`,"data":`)
	out.String(v.Data)
	out.RawByte('}')
}

// ===================================
// SafeBatchTransferFromPayload
// ===================================

func (v *SafeBatchTransferFromPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			v.From = string(in.String())
		case "to":
			v.To = string(in.String())
		case "ids":
			in.Delim('[')
			v.Ids = make([]string, 0)
			for !in.IsDelim(']') {
				v.Ids = append(v.Ids, string(in.String()))
				in.WantComma()
			}
			in.Delim(']')
		case "amounts":
			in.Delim('[')
			v.Amounts = make([]uint64, 0)
			for !in.IsDelim(']') {
				v.Amounts = append(v.Amounts, uint64(in.Uint64()))
				in.WantComma()
			}
			in.Delim(']')
		case "data":
			v.Data = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v SafeBatchTransferFromPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"from":`)
	out.String(v.From)
	out.RawString(`,"to":`)
	out.String(v.To)
	out.RawString(`,"ids":`)
	out.RawByte('[')
	for i, id := range v.Ids {
		if i > 0 {
			out.RawByte(',')
		}
		out.String(id)
	}
	out.RawByte(']')
	out.RawString(`,"amounts":`)
	out.RawByte('[')
	for i, amt := range v.Amounts {
		if i > 0 {
			out.RawByte(',')
		}
		out.Uint64(amt)
	}
	out.RawByte(']')
	out.RawString(`,"data":`)
	out.String(v.Data)
	out.RawByte('}')
}

// ===================================
// SetApprovalForAllPayload
// ===================================

func (v *SetApprovalForAllPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "operator":
			v.Operator = string(in.String())
		case "approved":
			v.Approved = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v SetApprovalForAllPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"operator":`)
	out.String(v.Operator)
	out.RawString(`,"approved":`)
	out.Bool(v.Approved)
	out.RawByte('}')
}

// ===================================
// BalanceOfPayload
// ===================================

func (v *BalanceOfPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "account":
			v.Account = string(in.String())
		case "id":
			v.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v BalanceOfPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"account":`)
	out.String(v.Account)
	out.RawString(`,"id":`)
	out.String(v.Id)
	out.RawByte('}')
}

// ===================================
// BalanceOfBatchPayload
// ===================================

func (v *BalanceOfBatchPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "accounts":
			in.Delim('[')
			v.Accounts = make([]string, 0)
			for !in.IsDelim(']') {
				v.Accounts = append(v.Accounts, string(in.String()))
				in.WantComma()
			}
			in.Delim(']')
		case "ids":
			in.Delim('[')
			v.Ids = make([]string, 0)
			for !in.IsDelim(']') {
				v.Ids = append(v.Ids, string(in.String()))
				in.WantComma()
			}
			in.Delim(']')
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v BalanceOfBatchPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"accounts":`)
	out.RawByte('[')
	for i, acc := range v.Accounts {
		if i > 0 {
			out.RawByte(',')
		}
		out.String(acc)
	}
	out.RawByte(']')
	out.RawString(`,"ids":`)
	out.RawByte('[')
	for i, id := range v.Ids {
		if i > 0 {
			out.RawByte(',')
		}
		out.String(id)
	}
	out.RawByte(']')
	out.RawByte('}')
}

// ===================================
// IsApprovedForAllPayload
// ===================================

func (v *IsApprovedForAllPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "account":
			v.Account = string(in.String())
		case "operator":
			v.Operator = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v IsApprovedForAllPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"account":`)
	out.String(v.Account)
	out.RawString(`,"operator":`)
	out.String(v.Operator)
	out.RawByte('}')
}

// ===================================
// MintPayload
// ===================================

func (v *MintPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "to":
			v.To = string(in.String())
		case "id":
			v.Id = string(in.String())
		case "amount":
			v.Amount = uint64(in.Uint64())
		case "maxSupply":
			v.MaxSupply = uint64(in.Uint64())
		case "soulbound":
			v.Soulbound = bool(in.Bool())
		case "data":
			v.Data = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v MintPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"to":`)
	out.String(v.To)
	out.RawString(`,"id":`)
	out.String(v.Id)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawString(`,"maxSupply":`)
	out.Uint64(v.MaxSupply)
	out.RawString(`,"soulbound":`)
	out.Bool(v.Soulbound)
	out.RawString(`,"data":`)
	out.String(v.Data)
	out.RawByte('}')
}

// ===================================
// MintBatchPayload
// ===================================

func (v *MintBatchPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "to":
			v.To = string(in.String())
		case "ids":
			in.Delim('[')
			v.Ids = make([]string, 0)
			for !in.IsDelim(']') {
				v.Ids = append(v.Ids, string(in.String()))
				in.WantComma()
			}
			in.Delim(']')
		case "amounts":
			in.Delim('[')
			v.Amounts = make([]uint64, 0)
			for !in.IsDelim(']') {
				v.Amounts = append(v.Amounts, uint64(in.Uint64()))
				in.WantComma()
			}
			in.Delim(']')
		case "maxSupplies":
			in.Delim('[')
			v.MaxSupplies = make([]uint64, 0)
			for !in.IsDelim(']') {
				v.MaxSupplies = append(v.MaxSupplies, uint64(in.Uint64()))
				in.WantComma()
			}
			in.Delim(']')
		case "soulbound":
			in.Delim('[')
			v.Soulbound = make([]bool, 0)
			for !in.IsDelim(']') {
				v.Soulbound = append(v.Soulbound, bool(in.Bool()))
				in.WantComma()
			}
			in.Delim(']')
		case "data":
			v.Data = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v MintBatchPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"to":`)
	out.String(v.To)
	out.RawString(`,"ids":`)
	out.RawByte('[')
	for i, id := range v.Ids {
		if i > 0 {
			out.RawByte(',')
		}
		out.String(id)
	}
	out.RawByte(']')
	out.RawString(`,"amounts":`)
	out.RawByte('[')
	for i, amt := range v.Amounts {
		if i > 0 {
			out.RawByte(',')
		}
		out.Uint64(amt)
	}
	out.RawByte(']')
	out.RawString(`,"maxSupplies":`)
	out.RawByte('[')
	for i, max := range v.MaxSupplies {
		if i > 0 {
			out.RawByte(',')
		}
		out.Uint64(max)
	}
	out.RawByte(']')
	out.RawString(`,"soulbound":`)
	out.RawByte('[')
	for i, sb := range v.Soulbound {
		if i > 0 {
			out.RawByte(',')
		}
		out.Bool(sb)
	}
	out.RawByte(']')
	out.RawString(`,"data":`)
	out.String(v.Data)
	out.RawByte('}')
}

// ===================================
// BurnPayload
// ===================================

func (v *BurnPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			v.From = string(in.String())
		case "id":
			v.Id = string(in.String())
		case "amount":
			v.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v BurnPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"from":`)
	out.String(v.From)
	out.RawString(`,"id":`)
	out.String(v.Id)
	out.RawString(`,"amount":`)
	out.Uint64(v.Amount)
	out.RawByte('}')
}

// ===================================
// BurnBatchPayload
// ===================================

func (v *BurnBatchPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			v.From = string(in.String())
		case "ids":
			in.Delim('[')
			v.Ids = make([]string, 0)
			for !in.IsDelim(']') {
				v.Ids = append(v.Ids, string(in.String()))
				in.WantComma()
			}
			in.Delim(']')
		case "amounts":
			in.Delim('[')
			v.Amounts = make([]uint64, 0)
			for !in.IsDelim(']') {
				v.Amounts = append(v.Amounts, uint64(in.Uint64()))
				in.WantComma()
			}
			in.Delim(']')
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v BurnBatchPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"from":`)
	out.String(v.From)
	out.RawString(`,"ids":`)
	out.RawByte('[')
	for i, id := range v.Ids {
		if i > 0 {
			out.RawByte(',')
		}
		out.String(id)
	}
	out.RawByte(']')
	out.RawString(`,"amounts":`)
	out.RawByte('[')
	for i, amt := range v.Amounts {
		if i > 0 {
			out.RawByte(',')
		}
		out.Uint64(amt)
	}
	out.RawByte(']')
	out.RawByte('}')
}

// ===================================
// URIPayload
// ===================================

func (v *URIPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			v.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v URIPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"id":`)
	out.String(v.Id)
	out.RawByte('}')
}

// ===================================
// SetURIPayload
// ===================================

func (v *SetURIPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			v.Id = string(in.String())
		case "uri":
			v.Uri = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v SetURIPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"id":`)
	out.String(v.Id)
	out.RawString(`,"uri":`)
	out.String(v.Uri)
	out.RawByte('}')
}

// ===================================
// SetBaseURIPayload
// ===================================

func (v *SetBaseURIPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "baseUri":
			v.BaseURI = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v SetBaseURIPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"baseUri":`)
	out.String(v.BaseURI)
	out.RawByte('}')
}

// ===================================
// ChangeOwnerPayload
// ===================================

func (v *ChangeOwnerPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "newOwner":
			v.NewOwner = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v ChangeOwnerPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"newOwner":`)
	out.String(v.NewOwner)
	out.RawByte('}')
}

// ===================================
// Response Types
// ===================================

// BalanceResponse
func (v BalanceResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"balance":`)
	out.Uint64(v.Balance)
	out.RawByte('}')
}

// BalanceBatchResponse
func (v BalanceBatchResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"balances":`)
	out.RawByte('[')
	for i, bal := range v.Balances {
		if i > 0 {
			out.RawByte(',')
		}
		out.Uint64(bal)
	}
	out.RawByte(']')
	out.RawByte('}')
}

// TotalSupplyPayload
func (v *TotalSupplyPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			v.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v TotalSupplyPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"id":`)
	out.String(v.Id)
	out.RawByte('}')
}

// MaxSupplyPayload
func (v *MaxSupplyPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			v.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v MaxSupplyPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"id":`)
	out.String(v.Id)
	out.RawByte('}')
}

// TotalMintedPayload
func (v *TotalMintedPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			v.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v TotalMintedPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"id":`)
	out.String(v.Id)
	out.RawByte('}')
}

// ExistsPayload
func (v *ExistsPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			v.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v ExistsPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"id":`)
	out.String(v.Id)
	out.RawByte('}')
}

// TotalSupplyResponse
func (v TotalSupplyResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"totalSupply":`)
	out.Uint64(v.TotalSupply)
	out.RawByte('}')
}

// MaxSupplyResponse
func (v MaxSupplyResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"maxSupply":`)
	out.Uint64(v.MaxSupply)
	out.RawByte('}')
}

// TotalMintedResponse
func (v TotalMintedResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"totalMinted":`)
	out.Uint64(v.TotalMinted)
	out.RawByte('}')
}

// ExistsResponse
func (v ExistsResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"exists":`)
	out.Bool(v.Exists)
	out.RawByte('}')
}

// IsSoulboundPayload
func (v *IsSoulboundPayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			v.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v IsSoulboundPayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"id":`)
	out.String(v.Id)
	out.RawByte('}')
}

// IsSoulboundResponse
func (v IsSoulboundResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"soulbound":`)
	out.Bool(v.Soulbound)
	out.RawByte('}')
}

// IsApprovedResponse
func (v IsApprovedResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"approved":`)
	out.Bool(v.Approved)
	out.RawByte('}')
}

// URIResponse
func (v URIResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"uri":`)
	out.String(v.Uri)
	out.RawByte('}')
}

// OwnerResponse
func (v OwnerResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"owner":`)
	out.String(v.Owner)
	out.RawByte('}')
}

// InfoResponse
func (v InfoResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"name":`)
	out.String(v.Name)
	out.RawString(`,"symbol":`)
	out.String(v.Symbol)
	out.RawString(`,"baseUri":`)
	out.String(v.BaseURI)
	out.RawString(`,"trackMinted":`)
	out.Bool(v.TrackMinted)
	out.RawByte('}')
}

// PausedResponse
func (v PausedResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"paused":`)
	out.Bool(v.Paused)
	out.RawByte('}')
}

// SuccessResponse
func (v SuccessResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"success":`)
	out.Bool(v.Success)
	out.RawByte('}')
}

// ===================================
// SupportsInterfacePayload (ERC-165)
// ===================================

func (v *SupportsInterfacePayload) UnmarshalTinyJSON(in *jlexer.Lexer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "interfaceId":
			v.InterfaceId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}

func (v SupportsInterfacePayload) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"interfaceId":`)
	out.String(v.InterfaceId)
	out.RawByte('}')
}

// SupportsInterfaceResponse
func (v SupportsInterfaceResponse) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"supported":`)
	out.Bool(v.Supported)
	out.RawByte('}')
}

// ===================================
// Event Types
// ===================================

// InitEvent
func (v InitEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// InitAttributes
func (v InitAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"owner":`)
	out.String(v.Owner)
	out.RawString(`,"name":`)
	out.String(v.Name)
	out.RawString(`,"symbol":`)
	out.String(v.Symbol)
	out.RawString(`,"baseUri":`)
	out.String(v.BaseURI)
	out.RawByte('}')
}

// TransferSingleEvent
func (v TransferSingleEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// TransferSingleAttributes
func (v TransferSingleAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"operator":`)
	out.String(v.Operator)
	out.RawString(`,"from":`)
	out.String(v.From)
	out.RawString(`,"to":`)
	out.String(v.To)
	out.RawString(`,"id":`)
	out.String(v.Id)
	out.RawString(`,"value":`)
	out.Uint64(v.Value)
	out.RawByte('}')
}

// TransferBatchEvent
func (v TransferBatchEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// TransferBatchAttributes
func (v TransferBatchAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"operator":`)
	out.String(v.Operator)
	out.RawString(`,"from":`)
	out.String(v.From)
	out.RawString(`,"to":`)
	out.String(v.To)
	out.RawString(`,"ids":`)
	out.RawByte('[')
	for i, id := range v.Ids {
		if i > 0 {
			out.RawByte(',')
		}
		out.String(id)
	}
	out.RawByte(']')
	out.RawString(`,"values":`)
	out.RawByte('[')
	for i, val := range v.Values {
		if i > 0 {
			out.RawByte(',')
		}
		out.Uint64(val)
	}
	out.RawByte(']')
	out.RawByte('}')
}

// ApprovalForAllEvent
func (v ApprovalForAllEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// ApprovalForAllAttributes
func (v ApprovalForAllAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"account":`)
	out.String(v.Account)
	out.RawString(`,"operator":`)
	out.String(v.Operator)
	out.RawString(`,"approved":`)
	out.Bool(v.Approved)
	out.RawByte('}')
}

// URIEvent
func (v URIEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// URIAttributes
func (v URIAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"value":`)
	out.String(v.Value)
	out.RawString(`,"id":`)
	out.String(v.Id)
	out.RawByte('}')
}

// OwnerChangeEvent
func (v OwnerChangeEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// OwnerChangeAttributes
func (v OwnerChangeAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"previousOwner":`)
	out.String(v.PreviousOwner)
	out.RawString(`,"newOwner":`)
	out.String(v.NewOwner)
	out.RawByte('}')
}

// PausedEvent
func (v PausedEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// PausedAttributes
func (v PausedAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"by":`)
	out.String(v.By)
	out.RawByte('}')
}

// UnpausedEvent
func (v UnpausedEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// UnpausedAttributes
func (v UnpausedAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"by":`)
	out.String(v.By)
	out.RawByte('}')
}

// BaseURIChangeEvent
func (v BaseURIChangeEvent) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"type":`)
	out.String(v.Type)
	out.RawString(`,"attributes":`)
	v.Attributes.MarshalTinyJSON(out)
	out.RawString(`,"tx":`)
	out.String(v.Tx)
	out.RawByte('}')
}

// BaseURIChangeAttributes
func (v BaseURIChangeAttributes) MarshalTinyJSON(out *jwriter.Writer) {
	out.RawByte('{')
	out.RawString(`"previousUri":`)
	out.String(v.PreviousURI)
	out.RawString(`,"newUri":`)
	out.String(v.NewURI)
	out.RawByte('}')
}
